### ISSUE TITLE
Can't pull much data hard to read Docs

### ISSUE THREAD

**Issue by KaiserWilhelm23** [mrvillage/pnwkit-py#16]
Seriously..... 

How do I pull average price data. 
and how many improvements each city might have like (coal mines or steel mills)

**Comment by mrvillage** [comment]
pnwkit-py is just a very light wrapper around generic GraphQL, you'd do it in almost exactly the same way. Write your query in the playground then take a look at some of the examples and just change the fields and parameters to make it do the same thing as your query in the playground.
